---
kind: Template
apiVersion: v1
labels:
  template: tracks-backend-template
metadata:
  name: backend-dc
  creationTimestamp:
parameters:
  - name: ENV_NAME
    displayName: Environment Name
    description: Environment Name
    required: true
  - name: CPU_REQUEST
    displayName: Requested CPU
    description: Requested CPU
    required: true
  - name: CPU_LIMIT
    displayName: CPU upper limit
    description: CPU upper limit
    required: true
  - name: MEMORY_REQUEST
    displayName: Requested memory
    description: Requested memory
    required: true
  - name: MEMORY_LIMIT
    displayName: Memory upper limit
    description: Memory upper limit
    required: true
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: tracks-backend
      labels:
        name: tracks-backend
        app: tracks
        env: ${ENV_NAME}
    spec:
      ports:
        - name: web-backend
          protocol: TCP
          port: 6005
          targetPort: 6005
      selector:
        name: tracks-backend
      type: ClusterIP
      sessionAffinity: None
    status:
      loadBalancer: {}
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      annotations:
        template.alpha.openshift.io/wait-for-ready: 'true'
      name: tracks-backend
      labels:
        name: tracks-backend
        app: tracks
        role: backend
        env: ${ENV_NAME}
    spec:
      replicas: 1
      strategy:
        type: Recreate
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - backend
            from:
              kind: ImageStreamTag
              name: 'tracks-backend:latest'
            type: imageChange
        - type: ConfigChange
      test: false
      selector:
        name: tracks-backend
      template:
        metadata:
          creationTimestamp:
          labels:
            name: tracks-backend
        spec:
          containers:
            - name: backend
              image: " "
              ports:
                - containerPort: 6005
                  protocol: TCP
              env:
                - name: NPM_RUN
                  value: 'serve'
                - name: TRACKS_DB_URL
                  value: 'jdbc:postgresql://tracks-postgresql:5432/tracks'
                - name: TRACKS_DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: tracks-database-secrets
                      key: DATABASE_USER
                - name: TRACKS_DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: tracks-database-secrets
                      key: DATABASE_PASSWORD
                - name: KEYCLOAK_CLIENT_ID
                  valueFrom:
                    configMapKeyRef:
                      name: tracks-keycloak-config
                      key: KEYCLOAK_CLIENT_ID
                - name: KEYCLOAK_REALM
                  valueFrom:
                    configMapKeyRef:
                      name: tracks-keycloak-config
                      key: KEYCLOAK_REALM
                - name: KEYCLOAK_URL
                  valueFrom:
                    configMapKeyRef:
                      name: tracks-keycloak-config
                      key: KEYCLOAK_URL
              resources:
                request:
                  cpu: "${CPU_REQUEST}"
                  memory: "${MEMORY_REQUEST}"
                limits:
                  cpu: "${CPU_LIMIT}"
                  memory: "${MEMORY_LIMIT}"
              readinessProbe:
                tcpSocket:
                  port: 6005
                initialDelaySeconds: 2
                timeoutSeconds: 3
                periodSeconds: 30
                successThreshold: 1
                failureThreshold: 3
              imagePullPolicy: IfNotPresent
              securityContext:
                capabilities: {}
                privileged: false
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
    status: {}
