kind: Template
apiVersion: v1
labels:
  template: tracks-configmaps-template
metadata:
  name: tracks-configmaps
parameters:
  - name: ENV_NAME
    displayName: Environment Name
    description: Environment Name
    required: true
  - name: JWT_ISSUER_URI
    required: true
  - name: KEYCLOAK_REALM
    required: true
  - name: KEYCLOAK_URL
    required: true
  - name: JWKS_URL
    required: true
objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: tracks-keycloak-config
    data:
      KEYCLOAK_CLIENT_ID: tracks-ui
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      JWT_ISSUER_URI: ${JWT_ISSUER_URI}
      JWKS_URL: ${JWKS_URL}
