kind: Template
apiVersion: v1
labels:
  template: tracks-database-secrets-template
metadata:
  name: tracks-database-secrets
parameters:
  - name: ENV_NAME
    displayName: Environment Name
    description: Environment Name
    required: true
  - name: DATABASE_PASSWORD
    required: true
  - name: DATABASE_REPLICATION_PASSWORD
    required: true
  - name: DATABASE_ROOT_PASSWORD
    required: true
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: tracks-database-secrets
    stringData:
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_REPLICATION_PASSWORD: ${DATABASE_REPLICATION_PASSWORD}
      DATABASE_REPLICATION_USER: replication
      DATABASE_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      DATABASE_USER: tracks
    type: Opaque
