---
kind: Template
apiVersion: v1
labels:
  template: tracks-gpx-processor-bc-template
metadata:
  name: gpx-processor-bc
  creationTimestamp:
parameters:
  - name: ENV_NAME
    displayName: Environment Name
    description: Environment Name
    required: true
objects:
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      annotations:
        description: Tracks GPX-Processor Image Stream
      name: tracks-gpx-processor
    spec:
      lookupPolicy:
        local: false
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      annotations:
        description: Tracks GPX Processor builder
      name: tracks-gpx-processor
    spec:
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: tracks-gpx-processor:latest
      postCommit: { }
      resources:
        limits:
          cpu: 2000m
          memory: 2G
        requests:
          cpu: 500m
          memory: 200M
      runPolicy: SerialLatestOnly
      source:
        contextDir: gpx_intake_processor
        git:
          uri: "https://github.com/bcgov/tracks.git"
          ref: "main"
        type: Git
      strategy:
        sourceStrategy:
          from:
            name: 'tracks-golang-s2i-builder:latest'
            namespace: dgsbmb-tools
        type: Source
    status:
      lastVersion: 0
