kind: Template
apiVersion: v1
labels:
  template: tracks-minio-secrets-template
metadata:
  name: tracks-minio-secrets-template
parameters:
  - name: ENV_NAME
    displayName: Environment Name
    description: Environment Name
    required: true
  - name: MINIO_ACCESS_KEY
    required: true
  - name: MINIO_SECRET_KEY
    required: true
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: tracks-minio-secrets
    stringData:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    type: Opaque
