---
kind: Template
apiVersion: v1
labels:
  template: tracks-minio-persistent-template
metadata:
  name: minio-tracks-dc
  creationTimestamp:
parameters:
  - name: ENV_NAME
    displayName: Environment Name
    description: Environment Name
    required: true
  - name: CPU_REQUEST
    displayName: Requested CPU
    description: Requested CPU
    required: true
  - name: CPU_LIMIT
    displayName: CPU upper limit
    description: CPU upper limit
    required: true
  - name: MEMORY_REQUEST
    displayName: Requested memory
    description: Requested memory
    required: true
  - name: MEMORY_LIMIT
    displayName: Memory upper limit
    description: Memory upper limit
    required: true
  - name: MINIO_PVC_SIZE
    value: 5G
    displayName: PVC Size
    description: PVC Size
    required: true
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: tracks-minio
      annotations:
        template.openshift.io/expose-uri: postgres://{.spec.clusterIP}:{.spec.ports[?(.name=="minio")].port}
      labels:
        name: minio
        app: tracks
        role: minio
        env: ${ENV_NAME}
    spec:
      ports:
        - name: minio
          protocol: TCP
          port: 9000
          targetPort: 9000
      selector:
        name: tracks-minio
      type: ClusterIP
      sessionAffinity: None
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: tracks-minio
      annotations:
        volume.beta.kubernetes.io/storage-class: netapp-block-standard
        template.openshift.io.bcgov/create: 'true'
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: "${MINIO_PVC_SIZE}"
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      annotations:
        template.alpha.openshift.io/wait-for-ready: 'true'
      name: tracks-minio
      labels:
        name: tracks-minio
        app: tracks-minio
        role: minio
        env: ${ENV_NAME}
    spec:
      replicas: 1
      strategy:
        type: Recreate
      triggers:
        - type: ConfigChange
      test: false
      selector:
        name: tracks-minio
      template:
        metadata:
          creationTimestamp:
          labels:
            name: tracks-minio
        spec:
          volumes:
            - name: minio-data
              persistentVolumeClaim:
                claimName: tracks-minio
          containers:
            - name: minio
              image: 'minio/minio'
              command:
                - minio
                - server
                - /export
              ports:
                - containerPort: 9000
                  protocol: TCP
              env:
                - name: MINIO_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: tracks-minio-secrets
                      key: MINIO_ACCESS_KEY
                - name: MINIO_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: tracks-minio-secrets
                      key: MINIO_SECRET_KEY
              resources:
                request:
                  cpu: "${CPU_REQUEST}"
                  memory: "${MEMORY_REQUEST}"
                limits:
                  cpu: "${CPU_LIMIT}"
                  memory: "${MEMORY_LIMIT}"
              volumeMounts:
                - name: minio-data
                  mountPath: "/export"
              readinessProbe:
                tcpSocket:
                  port: 9000
                initialDelaySeconds: 25
                timeoutSeconds: 1
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              imagePullPolicy: IfNotPresent
              securityContext:
                capabilities: {}
                privileged: false
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
    status: {}
